# Generated by Django 5.1.6 on 2025-04-08 19:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSenseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume locație')),
                ('ad_code', models.TextField(verbose_name='Cod AdSense')),
                ('is_active', models.BooleanField(default=True, verbose_name='Este activ')),
            ],
            options={
                'verbose_name': 'Locație AdSense',
                'verbose_name_plural': 'Locații AdSense',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Iconiță FontAwesome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresă')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Link Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Link Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Link YouTube')),
            ],
            options={
                'verbose_name': 'Setări Site',
                'verbose_name_plural': 'Setări Site',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conținut')),
                ('featured_image', models.ImageField(upload_to='articles/', verbose_name='Imagine principală')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data actualizării')),
                ('read_time', models.IntegerField(default=5, verbose_name='Timp de citire (minute)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Titlu Meta')),
                ('meta_description', models.TextField(blank=True, verbose_name='Descriere Meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Cuvinte cheie Meta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.category', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
                'ordering': ['-created_at'],
            },
        ),
    ]
