# Generated by Django 5.1.6 on 2025-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_adsenselocation_ad_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(default='Blogul nostru este dedicat pasionaților de fitness și nutriție care caută informații de calitate pentru un stil de viață sănătos.', verbose_name='Text secțiune despre'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(default='Despre noi', max_length=100, verbose_name='Titlu secțiune despre'),
        ),
    ]
