# Generated by Django 5.1.6 on 2025-04-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sitesettings_footer_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creării')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Este aprobat')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='Articol')),
            ],
            options={
                'verbose_name': 'Comentariu',
                'verbose_name_plural': 'Comentarii',
                'ordering': ['-created_at'],
            },
        ),
    ]
