# Generated by Django 5.1.6 on 2025-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text secțiune despre'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titlu secțiune despre'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL YouTube'),
        ),
    ]
