"""
Django settings for fitness_blog_new project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lbkje7_pf2q$k&s^%r&czr%f8=mu(p&y*z*_4e+95$@tc)c#(-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # Keep empty for local development initially


# Application definition

INSTALLED_APPS = [
    'jazzmin', # Added Jazzmin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps', # Added from old project
    'blog',                  # Added: our blog app
    'ckeditor',              # Added from old project
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fitness_blog_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Point to copied templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Added default
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.global_context', # Added from old project
            ],
        },
    },
]

WSGI_APPLICATION = 'fitness_blog_new.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ro' # Changed to Romanian

TIME_ZONE = 'Europe/Bucharest' # Changed timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/' # Added leading slash
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Point to copied static dir
]
# STATIC_ROOT is usually only needed for production collectstatic
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Define local media root

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Basic Jazzmin settings (customize later if needed)
JAZZMIN_SETTINGS = {
    "site_title": "Fitness Blog Admin",
    "site_header": "Fitness Blog",
    "welcome_sign": "Bine ai venit!",
    "copyright": "Fitness Blog",
    "search_model": ["blog.Article", "blog.Category"], # Example search models
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "blog.Article"},
        {"app": "blog"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "blog.Category": "fas fa-folder",
        "blog.Article": "fas fa-newspaper",
        "blog.NewsletterSubscriber": "fas fa-envelope",
        "blog.AdSenseLocation": "fas fa-ad",
        "blog.SiteSettings": "fas fa-cog",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    # "dark_mode_theme": "darkly", # Uncomment for dark mode option
}

# CKEditor Upload Settings
CKEDITOR_UPLOAD_PATH = "uploads/" # Subdirectory within MEDIA_ROOT
CKEDITOR_IMAGE_BACKEND = "pillow" # Use Pillow for image processing (optional)

# CKEditor Configuration to allow iframes (for video embeds)
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full', # Or 'Custom' if you want to define specific buttons
        'height': 300,
        'width': '100%',
        # Allow iframe tags and specific attributes needed for YouTube embeds
        'allowedContent': True, # Allow all content - simplest approach
        # More specific approach (if needed):
        # 'allowedContent': 'h1 h2 h3 p blockquote strong em;' +
        #                   'a[!href];' +
        #                   'img[!src,alt,width,height];' +
        #                   'iframe[src,width,height,frameborder,allowfullscreen,' +
        #                   'allow,title,referrerpolicy,loading];' + # Add necessary iframe attributes
        #                   'ul li;' +
        #                   'ol li;' +
        #                   'br;'
        # Add any other plugins or configurations here
        # 'extraPlugins': 'youtube', # Example if using a specific youtube plugin
    },
}
